
service: serverless-2024-prova
frameworkVersion: "3"

provider:
  name: AWS
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role: arn:aws:iam::058264440436:role/LabRole
  environment:
    DB_HOST: uf12-rds.cjucue2iqbwc.us-east-1.rds.amazonaws.com
    DB_USER: admin
    DB_PASSWORD: m3J5HAVaiF
    DB_PORT: 3306
    DB_NAME: AFP2024_Rocchio


functions:
  getAllPatients:
    handler: src/ospedale.getAllPatients
    events:
      - httpApi:
          path: /getAllPatients
          method: get
  getPazientiById:
    handler: src/ospedale.getPazientiById
    events:
      - httpApi:
          path: /getPazientiById/{id}
          method: get
  CreatePaziente:
    handler: src/ospedale.CreatePaziente
    events:
      - httpApi:
          path: /CreatePaziente
          method: post
  UpdatePaziente:
    handler: src/ospedale.UpdatePaziente
    events:
      - httpApi:
          path: /UpdatePaziente/{id}
          method: post
  DeletePazienti:
    handler: src/ospedale.DeletePazienti
    events:
      - httpApi:
          path: /DeletePazienti/{id}
          method: delete
plugins:
  - serverless-offline
  - serverless-plugin-typescript
