USE Ospedale;
INSERT INTO Stati (Id, Nome) VALUES
    (1, 'Notifica di ammissione/visita'),
    (2, 'Trasferimento di un paziente'),
    (3, 'Fine visita/dimissione'),
    (4, 'Registrazione di un paziente'),
    (5, 'Pre-ammissione di un paziente'),
    (6, 'Cambio di un paziente ambulatoriale in ricoverato'),
    (7, 'Cambio di un paziente ricoverato in ambulatoriale'),
    (8, 'Aggiornamento delle informazioni del paziente'),
    (9, 'Tracciamento della partenza del paziente'),
    (10, 'Tracciamento dell’arrivo del paziente'),
    (11, 'Annullamento della notifica di ammissione/visita'),
    (12, 'Annullamento del trasferimento'),
    (13, 'Annullamento della fine visita/dimissione'),
    (14, 'Ammissione in sospeso'),
    (15, 'Trasferimento in sospeso'),
    (16, 'Dimissione in sospeso'),
    (17, 'Scambio di pazienti'),
    (18, 'Unione delle informazioni del paziente'),
    (19, 'Query del paziente'),
    (20, 'Aggiornamento dello stato del letto'),
    (21, 'Il paziente va in congedo'),
    (22, 'Il paziente ritorna dal congedo'),
    (23, 'Cancellazione del record del paziente'),
    (24, 'Collegamento delle informazioni del paziente'),
    (25, 'Annullamento della dimissione in sospeso'),
    (26, 'Annullamento del trasferimento in sospeso'),
    (27, 'Annullamento dell’ammissione in sospeso'),
    (28, 'Aggiunta di informazioni sulla persona'),
    (29, 'Cancellazione delle informazioni sulla persona'),
    (30, 'Unione delle informazioni sulla persona'),
    (31, 'Aggiornamento delle informazioni sulla persona'),
    (32, 'Annullamento dell’arrivo del paziente - tracciamento'),
    (33, 'Annullamento della partenza del paziente - tracciamento'),
    (34, 'Unione delle informazioni del paziente - solo ID del paziente'),
    (35, 'Unione delle informazioni del paziente - solo numero di conto'),
    (36, 'Unione delle informazioni del paziente - ID del paziente e numero di conto'),
    (37, 'Scollegamento delle informazioni del paziente'),
    (38, 'Annullamento del pre-ricovero'),
    (39, 'Unione della persona - ID del paziente'),
    (40, 'Unione del paziente - elenco degli identificatori del paziente'),
    (41, 'Unione del conto - numero del conto del paziente'),
    (42, 'Unione della visita - numero della visita'),
    (43, 'Spostamento delle informazioni del paziente - elenco degli identificatori del paziente'),
    (44, 'Spostamento delle informazioni del conto - numero del conto del paziente'),
    (45, 'Spostamento delle informazioni sulla visita - numero della visita'),
    (46, 'Cambio dell’ID del paziente'),
    (47, 'Cambio dell’elenco degli identificatori del paziente'),
    (48, 'Cambio dell’ID alternativo del paziente'),
    (49, 'Cambio del numero del conto del paziente'),
    (50, 'Cambio del numero della visita'),
    (51, 'Cambio dell’ID alternativo della visita'),
    (52, 'Annullamento del congedo di un paziente'),
    (53, 'Annullamento del ritorno del paziente dal congedo'),
    (54, 'Cambio del medico curante'),
    (55, 'Annullamento del cambio del medico curante'),
    (60, 'Aggiornamento delle informazioni sull’allergia'),
    (61, 'Cambio del medico consulente'),
    (62, 'Annullamento del cambio del medico consulente');

